[BoundaryDofs]
"type" = "Element{:Seg2}"
"ğ“–"."type" = "SegGI5"

["Î©"]
"type" = "DiscreteElement{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."type" = "TriGI13"
"ğ“–"."ğ­" = "âˆ‡ğ­"

["Î©Ì„"]
"type" = "Element{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."type" = "TriGI13"
"ğ“–"."ğ­" = "ğ­"

["Î“áµ—"]
"type" = "Element{:Seg2}"
"ğ“’"."tag"  = "Î“áµ"
"ğ“–"."type" = "SegGI5"
"ğ“–"."ğ­" = "ğ­"
"ğ“–"."normal" = true

["Î“áµ"]
"type" = "DiscreteElement{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."tag"  = "Î“áµ"
"ğ“–"."type" = "SegGI5"
"ğ“–"."ğ­" = "âˆ‡ğ­"
"ğ“–"."normal" = true

["Î“"]
"type" = "DiscreteElement{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."type" = "SegGI5"
"ğ“–"."ğ­" = "ğ­"
