[BoundaryDofs]
"type" = "Element{:Seg2}"
"ğ“–"."type" = "SegGI5"

["Î©"]
"type" = "DiscreteElement{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."type" = "TriGI3"
"ğ“–"."ğ­" = "âˆ‡â‚‚ğ­"

["Î“áµ—"]
"type" = "DiscreteElement{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."tag" = "Î“áµ—"
"ğ“–"."type" = "SegGI5"
"ğ“–"."ğ­" = "ğ­"

["Î“áµ"]
"type" = "DiscreteElement{:Tri3}"
"ğ“’"."tag"  = "Î©"
"ğ“–"."tag" = "Î“áµ"
"ğ“–"."type" = "SegGI5"
"ğ“–"."ğ­" = "ğ­"
